apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world
  labels:
    app: python-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-hello-world
  template:
    metadata:
      labels:
        app: python-hello-world
    spec:
      containers:
      - name: python
        image: python:3.9
        command: ["python", "-m", "http.server", "5000"]
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: python-hello-world
